#!/bin/bash


version=`grep '<groupId>com.yahoo.ycsb</groupId>' pom.xml  -A 2 |grep '<version>' |sed 's/^.*>\(.*\)<.*$/\1/g'`
engine=mogucache-async
path=/tmp/

# mogucache/target/ycsb-mogucache-binding-0.9.0-SNAPSHOT.tar.gz
gzFileName=ycsb-$engine-binding-$version.tar.gz
gzFilePath=$engine/target/$gzFileName

# mvn -pl com.yahoo.ycsb:mogucache-binding -am clean package
mvn -pl com.yahoo.ycsb:$engine-binding -am clean package
if [ $? -ne 0 ] ; then
  echo err while mvn build
  exit -1
fi

if [ -f $gzFilePath ] ; then
  echo $gzFilePath exist
  echo rm -rf $path/ycsb-$engine*
  rm -rf $path/ycsb-$engine*
  echo cp $gzFilePath $path/
  cp $gzFilePath $path/
  cd $path/
  tar xvf $gzFileName
  echo rm -rf $gzFileName
  rm -rf $gzFileName
  exit 0
else
  echo $gzFilePath not exist
  exit -1
fi
